name: Build and Deploy WAR

on:
  push:

jobs:
  build:

    runs-on: self-hosted

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Build WAR File
        run: mvn clean package -DskipTests

      - name: Deploy WAR to Tomcat
        run: |
          copy target\*.war C:\Users\NARES\OneDrive\Desktop\apache-tomcat-9.0.117\webapps