name: Build Spring Boot Project

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Download Project Code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project
        run: mvn clean package -DskipTests